services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3Canto\CantoFal\:
    resource: '../Classes/*'

  TYPO3Canto\CantoFal\Browser\CantoAssetBrowser:
    shared: false
    public: true
    tags:
      - name: recordlist.elementbrowser

  TYPO3Canto\CantoFal\Hooks\DataHandlerHooks:
    public: true
    arguments:
      - '@TYPO3\CMS\Core\Registry'
      - '@cache.canto_folder'
      - '@cache.canto_file'

  TYPO3\CMS\Backend\Form\Container\FilesControlContainer:
    public: true

  TYPO3Canto\CantoFal\Resource\Repository\CantoRepository:
    public: true
    arguments:
      - '@TYPO3\CMS\Core\Registry'
      - '@cache.canto_folder'
      - '@cache.canto_file'

  TYPO3Canto\CantoFal\Resource\Metadata\Extractor:
    public: true

  TYPO3Canto\CantoFal\Resource\Processing\CantoPreviewProcessor:
    public: true

  TYPO3Canto\CantoFal\Resource\Processing\CantoMdcProcessor:
    public: true

  TYPO3Canto\CantoFal\Controller\Backend\CantoAssetBrowserController:
    public: true

  TYPO3Canto\CantoFal\Resource\MdcUrlGenerator:
    public: true

  TYPO3Canto\CantoFal\Resource\Metadata\Exporter:
    public: true

  TYPO3Canto\CantoFal\Resource\Repository\CantoAlbumRepository:
    arguments:
      - 'sys_file_canto_album'
      - '@TYPO3\CMS\Core\Database\ConnectionPool'

  TYPO3Canto\CantoFal\Command\WarmupCantoCache:
    calls:
      - injectStorageRepository: ['@TYPO3\CMS\Core\Resource\StorageRepository']
      - injectCantoFolderCache: ['@cache.canto_folder']
    tags:
      - name: 'console.command'
        command: 'canto:warmupcache'

  TYPO3Canto\CantoFal\Command\UpdateMetadataAssetsCommand:
    calls:
      - injectCantoFileCache: [ '@cache.canto_file' ]
    tags:
      - name: 'console.command'
        command: 'canto:updatemetadataassets'

  TYPO3Canto\CantoFal\Command\UpdateImageAssetsUsedInFrontendCommand:
    calls:
      - injectCantoFileCache: ['@cache.canto_file']
    tags:
      - name: 'console.command'
        command: 'canto:updateusedmetadataassets'

  TYPO3Canto\CantoFal\Command\RemoveMdcPrefixForFilesCommand:
    tags:
      - name: 'console.command'
        command: 'canto:removemdcprefixforfiles'

  TYPO3Canto\CantoFal\Command\MigrateFileIdentifiersToNewFormat:
    tags:
      - name: 'console.command'
        command: 'canto:migratefileidentifiers'

  TYPO3Canto\CantoFal\Resource\EventListener\AddDomainsToContentSecurityPolicyEventListener:
    tags:
      - name: event.listener
        identifier: addDomainsToContentSecurityPolicyEventListener
        event: TYPO3\CMS\Core\Security\ContentSecurityPolicy\Event\PolicyMutatedEvent

  TYPO3Canto\CantoFal\Resource\EventListener\HandleMultipleFolders:
    tags:
      - name: event.listener
        identifier: updateFoldersAfterFileAddedToIndexEvent
        event: TYPO3\CMS\Core\Resource\Event\AfterFileAddedToIndexEvent
        method: afterFileAddedToIndexEvent
      - name: event.listener
        identifier: updateFoldersAfterFileUpdatedInIndexEvent
        event: TYPO3\CMS\Core\Resource\Event\AfterFileUpdatedInIndexEvent
        method: afterFileUpdatedInIndexEvent

  TYPO3Canto\CantoFal\Resource\EventListener\GeneratePublicUrlForResourceEventListener:
    tags:
      - name: event.listener
        identifier: generatePublicUrlForMdcFiles
        event: TYPO3\CMS\Core\Resource\Event\GeneratePublicUrlForResourceEvent

  TYPO3Canto\CantoFal\Resource\EventListener\ForceJpgPreviewImage:
    tags:
      - name: event.listener
        identifier: forceCantoJpegPreview
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent

  TYPO3Canto\CantoFal\Resource\EventListener\MetadataWebhookEventListener:
    tags:
      - name: event.listener
        identifier: metadataWebhookEventListener
        event: TYPO3Canto\CantoFal\Resource\Event\IncomingWebhookEvent

  TYPO3Canto\CantoFal\Resource\EventListener\NewAssetVersionWebhookEventListener:
    tags:
      - name: event.listener
        identifier: newAssetVersionWebhookEventListener
        event: TYPO3Canto\CantoFal\Resource\Event\IncomingWebhookEvent

  TYPO3Canto\CantoFal\Resource\EventListener\DeleteAssetWebhookEventListener:
    tags:
      - name: event.listener
        identifier: deleteAssetWebhookEventListener
        event: TYPO3Canto\CantoFal\Resource\Event\IncomingWebhookEvent

  TYPO3Canto\CantoFal\Resource\EventListener\BeforeFileProcessingEventListener:
    arguments:
      - "@TYPO3Canto\\CantoFal\\Resource\\Repository\\CantoRepository"
      - "@TYPO3\\CMS\\Core\\Resource\\ProcessedFileRepository"
      - "@TYPO3Canto\\CantoFal\\Resource\\MdcUrlGenerator"
    tags:
      - name: event.listener
        identifier: cantoMdcProcessingFileEnricher
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent

  TYPO3Canto\CantoFal\Resource\EventListener\AfterFormEnginePageInitializedEventListener:
    tags:
      - name: event.listener
        identifier: afterFormEnginePageInitializedEventListener
        event: TYPO3\CMS\Backend\Controller\Event\AfterFormEnginePageInitializedEvent


  TYPO3Canto\CantoFal\Resource\EventListener\SyncMetaDataCategoriesEventListener:
    tags:
      - name: event.listener
        identifier: 'synchronizeFileMetaDataCategoriesAfterCreation'
        method: 'afterFileMetaDataCreated'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataCreatedEvent
      - name: event.listener
        identifier: 'synchronizeFileMetaDataCategoriesAfterUpdate'
        method: 'afterFileMetaDataUpdated'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataUpdatedEvent

  TYPO3Canto\CantoFal\Resource\EventListener\SyncMetaDataTranslationsEventListener:
    tags:
      - name: event.listener
        identifier: 'synchronizeFileMetaDataTranslationsAfterCreation'
        method: 'afterFileMetaDataCreated'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataCreatedEvent
      - name: event.listener
        identifier: 'synchronizeFileMetaDataTranslationsAfterUpdate'
        method: 'afterFileMetaDataUpdated'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataUpdatedEvent


  cache.canto_folder:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    public: true
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['canto_fal_folder']

  cache.canto_file:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    public: true
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'canto_fal_file' ]
